title: Đặng Tiến Sĩ
description: Blog cá nhân của lập trình viên Đặng Tiến Sĩ.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dangtiensi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Facebook":
    - "//fb.com/file.json"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; Đặng Tiến Sĩ"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

ga_tracking: UA-2709176-10

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
